import scikitplot as skplt
import matplotlib.pyplot as plt

y_true = [1, [0] * 10 + [1] * 10]# ground truth labels
y_probas = [[1] * 20]# predicted probabilities generated by sklearn classifier
print(y_true.size)
skplt.metrics.plot_roc_curve(y_true, y_probas)
plt.show()